### ISSUE TITLE
NegativeArraySizeException keeps crashing my server

### ISSUE THREAD

**Issue by marcelschoen** [SpigotPlugins-xuancat0208/FartherViewDistance#2]
I run version 9.7.3 of this plugin on my Paper 1.19.2 server. The server keeps crashing shortly after I connect with a player, with this exception:
```
java.lang.NegativeArraySizeException: -1
	at java.util.HashMap$KeySet.toArray(Unknown Source) ~[?:?]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:265) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.world.level.chunk.LevelChunk.postProcessGeneration(LevelChunk.java:1084) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk.lambda$onNeighbourChange$1(LevelChunk.java:214) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.doRunTask(ServerChunkCache.java:993) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1003) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:578) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1329) ~[paper-1.19.2.jar:git-Paper-258]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-258]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.2.jar:git-Paper-258]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-258]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-258]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[09:14:53 ERROR]: Encountered an unexpected exception
java.lang.NegativeArraySizeException: -1
	at java.util.HashMap$KeySet.toArray(Unknown Source) ~[?:?]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:265) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.world.level.chunk.LevelChunk.postProcessGeneration(LevelChunk.java:1084) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk.onChunkTicking(LevelChunk.java:883) ~[?:?]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1319) ~[paper-1.19.2.jar:git-Paper-258]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1050) ~[paper-1.19.2.jar:git-Paper-258]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1034) ~[paper-1.19.2.jar:git-Paper-258]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:919) ~[paper-1.19.2.jar:git-Paper-258]
	at net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:582) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1000) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:578) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickMidTickTasks(MinecraftServer.java:2715) ~[paper-1.19.2.jar:git-Paper-258]
	at net.minecraft.server.MinecraftServer.executeMidTickTasks(MinecraftServer.java:2738) ~[paper-1.19.2.jar:git-Paper-258]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.2.jar:git-Paper-258]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-258]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-258]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-258]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-258]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```
While it doesn't seem like any class from  "FartherViewDistance" is in this stacktrace, the crashes stop as soon as I disable the plugin.

**Comment by marcelschoen** [comment]
I'm using a docker image created by someone else, so it may sometimes be a little bit behind. I just tested (and reproduced the crash) again; running "/version" in the console gave me:

```
This server is running Paper version git-Paper-265 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git:117579c)
You are running the latest version
```

**Comment by marcelschoen** [comment]
Actually, with the default configuration, it doesn't crash. So it must be one of the settings I changed. I will try further and let you know when I identify it.
